### ISSUE TITLE
Mopidy track control

### ISSUE THREAD

**Issue by happyleavesaoc** [badaix/snapcast#23]
Hi, first off, this is a fantastic initiative. Very happy to have found it.

I'm using it in conjunction with Mopidy, but I'm experiencing a problem with track control. If I hit pause/play/next/prev in Mopidy, my clients report:
```
2016-01-12 22-44-45 [out] Failed to get chunk
2016-01-12 22-44-49 [out] time sync main loop
```
No errors in the server.

Accompanying this on one of my clients is some audio artifacting - it sounds like it is playing back the last chunk in an infinite loop (I suspect this is actually a separate issue?)

If I let Mopidy transition to the next track without manual intervention, it works fine. I'm guessing this is more of a Mopidy problem than a snapcast problem, but I wanted to document the issue here just in case/as a note for other Mopidy users.

**edit:** I followed up on this with Mopidy - the track control is certainly a Mopidy issue, but this issue is still relevant due to the audio artifacting.

**Comment by badaix** [comment]
Hi,

is this related to issue #11?

**Comment by happyleavesaoc** [comment]
The Mopidy track control issues are actually a follow-on issue related to the fix they implemented for the gapless playback mentioned in #11. So in that way they are related. Probably relevant to users of snapcast+Mopidy, but not a snapcast issue.

The audio artifacting could be a snapcast issue though (but of course only triggered by an issue in an upstream program - so maybe not a priority).

**Comment by happyleavesaoc** [comment]
This Mopidy problem has been resolved in the `develop` Mopidy branch.

**Comment by badaix** [comment]
It should also be fixed with this commit 73a9223c6fd578e46e8f52549293af651ce8ffa8 in Snapcast's `develop` branch

**Comment by happyleavesaoc** [comment]
I'm on the latest `develop`, but I still get audio artifacting on one of my clients when I pause my source audio. It sounds like the last chunk is being replayed over and over again. It only stops when I stop the client process. Should I open a new issue for this? Is there a config option or some testing I can do to solve this problem?
